### ISSUE TITLE
joyBonnet.py: "1" and "2" keys are swapped

### ISSUE THREAD

**Issue by ruuddotorg** [adafruit/Adafruit-Retrogame#43] opened 2017-04-12 00:50 UTC
On my joy bonnet (attached to a Pi Zero W), pressing the "1" key on the PCB generates a "2" keyboard press and vice versa.
Trivial to fix by swapping the key codes in joyBonnet.py, but I was wondering if this is a known issue?

**Comment by PaintYourDragon** [comment] 2017-04-13 19:36
Yep, something of a typo going back to the schematic. Fixed in the code now (swapped the GPIO pin numbers rather than the keycodes, so PLAYER1 is GPIO23 as intended and keycode is '1'...but basically same effect in the end...I mean, RetroPie doesn't really care once they inputs are assigned...those could be '7' and right-Alt key, but I see how it could cause confusion in other applications).

**Closed by PaintYourDragon** 2017-04-13 19:36 UTC
